// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1SGYAYbUJoRhl4Zs8Ud25G5c5vqftLU',
    appId: '1:832600825780:web:18f16c6f49dd2247ebdce1',
    messagingSenderId: '832600825780',
    projectId: 'bisim-app-e76f1',
    authDomain: 'bisim-app-e76f1.firebaseapp.com',
    storageBucket: 'bisim-app-e76f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljA4F4K3nVpduSkzLxF4TPQF6qzJPwk0',
    appId: '1:832600825780:android:2509e82382eaef05ebdce1',
    messagingSenderId: '832600825780',
    projectId: 'bisim-app-e76f1',
    storageBucket: 'bisim-app-e76f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp1TKJin7jMwdNmbLv728VjcS3AF-zAiE',
    appId: '1:832600825780:ios:fb96ac8e266bf47febdce1',
    messagingSenderId: '832600825780',
    projectId: 'bisim-app-e76f1',
    storageBucket: 'bisim-app-e76f1.appspot.com',
    iosClientId: '832600825780-kivsgn5e4va2dlghndpemm9jn52ik9ru.apps.googleusercontent.com',
    iosBundleId: 'com.samilnugay.yenibisim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp1TKJin7jMwdNmbLv728VjcS3AF-zAiE',
    appId: '1:832600825780:ios:e99ad18577d18388ebdce1',
    messagingSenderId: '832600825780',
    projectId: 'bisim-app-e76f1',
    storageBucket: 'bisim-app-e76f1.appspot.com',
    iosClientId: '832600825780-97kvhlptf93g90vrfodu30246cb9k0aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.yenibisim',
  );
}
